#ifndef ACOLITOJSON_GLOBAL_H
#define ACOLITOJSON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACOLITOJSON_LIBRARY)
#  define ACOLITOJSONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACOLITOJSONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACOLITOJSON_GLOBAL_H
